version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  express_backend:
    build: ./back-end
    ports:
      - 8080:8080

  react_frontend:
    build:
      context: ./front-end
      args:
          nginx_config_file: default.local.conf
    ports:
      - 8081:80

volumes:
  mongodb_data_container: